version: '3.8'

services:
  web:
    build: .
    command: gunicorn text_shuffle.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A text_shuffle worker -l info
    volumes:
      - .:/app
      - media:/app/media
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
  media:
